apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: 200148130345.dkr.ecr.ap-northeast-2.amazonaws.com/python:89513af485f2593e367f138f3ba13e9f8619ed04
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sample
  namespace: dev
spec:
  selector:
    app: sample
  ports:
  - port: 80
    targetPort: 8080
